[package]
name = "owmods_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opener = "0.5.0"
directories = "4.0.1"
reqwest = { version = "0.11.14", features = ["blocking"] }
glob = "0.3.1"
version-compare = "0.1.1"
async-recursion = "1.0.2"
anyhow = "1.0.68"
zip = { version = "0.6.3", default-features = false, features = [ "deflate", "zstd", "bzip2" ] }
tempdir = "0.3.7"
